services:
  php:
    build:
      context: ../../..
      dockerfile: docker/infrastructure/dev/php/Dockerfile
      args:
        - USER=${USER:-someone}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    pull_policy: never
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}-php
    volumes:
      - ../../../backend:/var/www/html
    tty: true
    restart: unless-stopped
    depends_on:
      - db
      - nginx
    networks:
      - backend-network

  db:
    image: mysql:9.0.1
    pull_policy: never
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}-db
    environment:
      - MYSQL_DATABASE=${DOCKER_DB_DATABASE}
      - MYSQL_USER=${DOCKER_DB_USERNAME}
      - MYSQL_PASSWORD=${DOCKER_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_PASSWORD}
    ports:
      - "${DOCKER_DB_PORT}:3306"
    volumes:
      - dev-db-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - backend-network


  nginx:
    build:
      context: ../../..
      dockerfile: docker/infrastructure/dev/nginx/Dockerfile
    pull_policy: never
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}-nginx
    ports:
      - "8080:80"
    volumes:
      - ../../../backend:/var/www/html
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
    name: backend-network

volumes:
  dev-db-data:
    driver: local
    name: dev-db-data
