name: Backend App Checks

on:
  push:
    branches: ["feature/setup-git-workflows"]
#      - main
#      - staging
#      - production
  pull_request:
    branches: ["feature/setup-git-workflows"]
#      - main
#      - develop
#      - staging
#  release:
#    types: [published]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        run: make dev-build
      - name: Starts The Docker Images
        run: make dev-up
      - name: Check Running Containers
        run: docker ps -a
