name: Backend App Checks

on:
  push:
    branches: ["feature/setup-git-workflows"]
#      - main
#      - staging
#      - production
  pull_request:
    branches: ["feature/setup-git-workflows"]
#      - main
#      - develop
#      - staging
#  release:
#    types: [published]

jobs:
  build_backend:
    name: Build Backend App
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        # Backend folder working directory.
#        working-directory: backend
    steps:
      - uses: actions/checkout@v4
# Use filter if project contains separated frontend app
#      - uses: dorny/paths-filter@v2
#        id: filter
#        with:
#          filters: |
#              Mobile:
#                - 'frontend/**'
#      - name: Get npm dependencies.
#        if: steps.filter.outputs.frontend == 'true'
#        run: npm install
      - name: Build The Docker Images
        run: make dev-build
      - name: Run The Docker Images
        run: make dev-up
      - name: Check Running Containers
        run: docker ps -a
